<script>
export default {
  name: "TagImage",
  data() {
    return {
      api_url: "https://picsum.photos/1024/768",
      url_headers: ["Access-Control-Allow-Origin: *", "mode: no-cors"],
      image_count: null,
      image_list: null,
      image_tags: ['Blades', 'Bombs', 'Bow and Arrow', 'Bullet Boxes', 'Bullet Cells', 'Full_face_hoods', 'Injectable_Drug', 'Knives', 'Military_Clothing', 'Pcp_airguns', 'Pils Drug', 'Pistols', 'Powder_Drug', 'Revolver', 'Rifles', 'Rockets', 'Seeds', 'Shotgun', 'War Accessories', 'Weapon_Cases', 'Weapon_Magazines', 'Weapon_Storage', 'Weeds'],
      image_tag: null
    };
  },
  methods: {
    getSelectedTag(index) {
      console.log("selected index is " + index);
      let selected_tag = this.image_tags[index];
      console.log("selected tag is " + selected_tag);
      this.image_tag = selected_tag;
      this.getSimilarImages(selected_tag);
      // return this.api_url;
    },
    async getSimilarImages(tag) {
      let base_url = 'http://10.100.52.103:8000/';
      let endpoint = 'images/classification';
      let api_url = base_url + endpoint + '?label=' + tag + '&num_images=' + this.image_count;
      console.log(api_url);

      const requestOptions = {
        method: "GET",
        redirect: "follow",
      };

      const response = await fetch(api_url, requestOptions);

      this.api_data = await response.json();
      console.log("API Response Status:", this.api_data);

      this.image_list = this.api_data["files"].map((file) => {
        return {
          "img_src": base_url + file,
        };
      });
    },
    async getRandomImage() {
      // let response = await fetch("https://api.api-ninjas.com/v1/randomimage?category=technology", {method: "GET", mode: "no-cors", headers: {"X-Api-Key": "53MdYc1WN6MSjm5wg+7QOA==uRs2Omvh6AMf7hIa", "Accept": "image/jpg"}})
      let response = await fetch("https://picsum.photos/500/300");
      console.log("random image fetch");
      console.log(response.url);
      let image_url = response.url;
      return image_url;
    },
    async getRandombase64Image() {
      let base64_images = [
        'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXi6/Q9X3GcY47HJd4oS7oZktdtQLRaUoxte1WFC3BVWXYLSh4wTKLa5m0Tkuqq4YEZ+3Wdc4aq1SqtXWzuC7eQA22BaR4WwvtDqusO2AWLpnQihgGipHur3iSJc/r9Qc83+Sc3znvfAYnnj5+VNKPTjo1uv/oB8+I7m/+yM+i+3M2nBnd/82f3xfdf+KhV6P724ffie6v+MvPRPe//sKT0f2Lz/hCdH/52k9H91d94Lbo/pfm/0V0/+njH4nuL7hlcnT/sOg6AP9vCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgNvPLQ1+sCqxz8b3R/9wLuj+9+55LvR/eFl/xjdf+H4+dH9wUufiO4Pbb43un/D2Q9F95cc+d/R/QkrPxzdX3jivOj+50f+Prp/xamnRffX3X5jdH/crDui+y4AgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKDUwN3TNkQfWDNpZXR/wdTLo/trHojOj/rICTdF90+efUx0/zNTbovuv3bD69H9JTdtje4PT740uj9/9o+j+5uW3RzdX3Te1Oj+C/f8aXT/787dFd2fPOf06L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNbDu3JOiD1z0rf+M7k8fNxTd/9THT43un/axJ6P7Y9Y9Et1/9cGR6P7HPrs1uv+9C7M/n1lDK6L7M//4uuj+fz2zO7p/19JvRPdH3toc3d9z21PR/d/54Z3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBq4L0PnxJ9YM/v3Rbdf/Qbb0b3v3XUxOj+5VNGR/dfO/S30f0vfPP56P4dIzOj+z8f/eXo/iu7pkX3PzfpQHT/9j+6Pro//P3PRfd3Hjwmuj/9Syuj+9efvzi67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/tW966IPTD/i7uj+0KyF0f3B6Xuj+5f+04nR/Td/enJ0/9r3HRXdP2fStuj+tokvRvfHLN4X3X923/Lo/pyhg9H9i/5nY3R/+XvmRve/ffY10f3Rn98T3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBs5Yujv6wN51O6P7t378UHT/gq0/ju7/asLB6P5XP7E3uj9w4Mjo/o1LHo7ujxw7Prr/+2O2R/fnLnwqur/qxPXR/XX3nhLdf+fxtdH9GUtuiu5fNntedN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGlz/ydOiD7z9z49F95+78JvR/fuXfj+6f8f4s6L7hz/5W9H9917zZnT/sKe2RfcPnfpOdP+Gs7dH94+a8ono/tULLojuX3/CsdH9x/ZfEt0fHNkQ3T/2lLui+y4AgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKDUwKqXH4s+cM/GFdH9cS8ti+5/6In50f0n7jsU3f/11hej++9/Pfv7fffR10f3/3DiUdH9Gy5bG93fMuOy6P5fD+yP7v/qxY3R/flL7o/uf3rTsdH9//jdidF9FwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGpg7IMTog9c+fCW6P624ZHo/huLvhLdv27ZydH97111THT/kcMmRfcvfuai6P6Co5+O7h935J3R/YkvrY/uH3f0juj+ldOuje6/vXpNdP+snbdG9w9tmh7ddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGH5m/JvrAwpuHovurv7siun/anJXR/eVfHI7uL75uTHR/1w/Pi+6PenV3dP6paTui+z+75wfR/SOuHhvdX3PrjOj+VYcPRPffdefO6P7jc8+M7k/ZnP0+XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnByyfPij7w66GXo/uLT/qz6P6uB++K7g8eujy6/8Exq6P792y+ILr/71fNiO7vfnYguv/AL/81un/1fW9F9xf9ck50/5m52f8/I9/+SXT/vDHLo/tXPHt+dN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGli8cWb0gXPGHozuP/+Tr0T3z5z2RnR/86eOiO6f/sqE6P7e1ydH90etmhGd/9rBE6L723Z9KLr/N4s+EN3ftGp8dP+Kedm/rysP/SK6v+zASdH98/ddEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQZv/uik6AOvzf5RdH/HwrOj+8/9y0vR/RuP+7fo/nnnnhjdHzfxf6P7b5/yD9H9qV++P7q/ZGr2+xy1fX50/pO33B3d/4N9+6L7K386Nbo/9sCd0f3HPnp4dN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGvzwy+OiD/zJgeOj+7POGYnuT7np+ej+ydccHt0ffi46P+rCkbOi+99ZenN0f/TSR6P773tgOLq/8OKvR/cXbdkR3X/6/XOj+7e8cnd0f86Te6L7b23/TXTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBrc/9UJ0Qf2/WJ3dH/xe7ZE9782+vbo/rULZ0b3lw1cGd1fO29DdH/Fzwei+2MX7I/uH3/+vOj+orVfjO7PfNcPovsHx6+P7l/z20dH92cPjUT3x168OrrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASv1fAAAA//+ouYXNbvaFhwAAAABJRU5ErkJggg==',
        'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXjdfXdX3H8dh+rikzaTabNupkN2eJojKNw8EVZoEdJZ23Q7KmYaPQQ+tUsgQV2IJGNhfLSTdkqZtrzLNK5Jjm3UmdJhc5SyhSLxcCByUFuTZoF7q/4nVO57wejz/g9Tnnd76/8zzvwewDPviqpH/a8LXo/v+NXB3dn3/kiuj+x2beGt1//+9tiO6vecPm6P6UN74U3X9w/oTo/iXPfzK6/8up/xrd/9qex6P7l638m+j+0Pl/Gd2fdNFj0f15izZF938rug7AbywBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqzDHTZkQfOHTnFdH9GV/87+j+9tuPje6/8NEnovsvnbYvur9i2kPR/XftWRTdv+yge6P779i1P7p/8Mybovtr3ntddH/nYGl0/6zhB6L79zxxTXR/0l99ILrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg0uf/A90Qe+MDwrun/qkvOj+08seGd0/+jvPhDdP+2H90b3L1u9MLp/95xvRPcPO21qdP/fbxob3Z/+puHo/oS9F0T3H1329ej+kjfOjO5POveG6P7uL90W3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBidO3Bx94EvfPDq6P2nRluj++dd+Nbp/yQWvj+7vvWg0uv/7M66O7o9dPza6f+Yh06L7v/34xdH9kc8ORfeP3Lokuv++1euj+2//2cvR/a8eM4juDz+1MLrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg12bbs9+sDWX54R3Z98253R/fGvfj66f8CHp0b35958a3R/zinLovvHX/JAdH/x+H3R/VNOnxndv+UPvh7dH37Hk9H95bO2Rfdn/fjl6P7ItQui+6N3fia67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN5n96XfSBa75zRHR/6YwJ0f3pix+J7v/Z95dF99+/6vLo/j0jS6P7u9/zqej+gStfG93//J4Z0f2N39wf3Z/287HR/c8fe310/6fP7Yju3732x9H9m486OrrvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASo353hX3Rx8Y2rQ7ur9l62ei+8PHXR3dv2Pd09H90Yc/EN0/evTB6P67R14X3Z/55nXR/ZMefzG6v/zwzdH9WY/PjO4/deC7ovuHrL05ur/vmVnR/ROfzn4/LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNRg8uVnRh+4bON50f3VH3o5ur/ygbOi+w+NOT66f8sPJ0b3H5771uj+2tk/iO6f/tNvRPe3LDksuz/3oej+gikbovt7102J7r/p9B3R/a33PxXdX7x+UnTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBrccddHog8sHX9zdP+P538luj9myYTo/kcvvD26v/3j34ruL168M7o/7ZgbovsXPvkX0f1fjLsyuv+H970hun/jn/4kun/dunui+8f83fzo/gE3ZX//8WuPiu67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUmPmvW5F9IHZs2+M7p93wV3R/fW3vBTdP2NoXnT/W+f+bXR/8pqJ0f2TVq+M7r/w9Iei+/d8+eTo/opvXxzdn758V3R/+Zjs/+vhrY9G9zc8vzG6v+Tqg6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTgwSlD0Qf27l4W3b936Pjo/sgnvhjdP3TH4dH9cUecHd0fPfEj0f2JJ1wb3X/mlS9H92/Yl/0+z7j+NdH9iY9+L7q/ee+i6P7Quc9E9+86Mvt9bjryoOi+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDX42Lv/J/rAt0ez+1/ZGZ1/1cXn74/uH7X92Oj+6MKF0f01562K7t/2wUei+7deMT+6/8lNR0T3f2fM96P7j12V/X12vX5DdP/V486O7s9788+i+5ce+GR03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavLBvf/SBCR8fF92/amh9dH/65lOi+8MjE6P7nz1zdnT/2StPje7f9KuTo/tXvvLh6P7fr5wX3b/x0tXR/VUb/yu6P+PaHdH9X8+5Krp/97hXovsn3fdH0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavC2A8ZHHzj11s9F96c+9NfR/eGRt0b3f/ecVdH9L3zn0uj+3vvfFt3/7vg7ovsTp8yN7k9edHh0/+FzTonuX/fet0f3T533o+j+faO/iO4PLs5+P9MWPBfddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGS9ceG33g4BP+Obr/vouuie5/+p0nRvd/tfy56P704z4R3X/LspOj+69dMS+6f/iFfxLdv/Jzh0T3p977ZHR/zdkvRve3/uD66P7Cke3R/X846LDo/gn/m/1/uQAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDkXGLog/8y3H/Ed3/+eRDo/urDvlRdP/FO98S3d/02Nzo/tgN/xbd37htXHR/zk/+Mbq/fsG26P62T/15dH/PXedE9888a050/9e7H4nuP/ufW6L7M17zbHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlPr/AAAA//8MrpXBjuZJEwAAAABJRU5ErkJggg==',
        'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXjdfXdX3H8S69luQRFy2zlnizcZGwZuI54mweS8hTW6aiC+SgHkUm4m1aRpPccXVkDG82zxKzWeE0FdOlJzUN1HYa6aHmIgYoFwZGxYEkaNgCYrC/4nVO57wejz/g9bnOub7n9zzvwcO/9uCbkv767Yui+zeMnxndn7R9dnT/sTk3Rfe/OvfM6P77x/0wuv+TjWOj+/MmfSy6/8KCT0X3P/3zR6P7S1+aFd0/5vYZ0f0jF46L7s8efjK6/6WrXo/uHxBdB+B3lgAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDWw+OSN0Qf+7IVJ0f1HH/9odH/N0wuj+7e8fWJ0f9vS/4juLxg/Mrr/3NCE6P6i4Y9H97+95Jzo/vblfx7dP/Fvvxjdv3DZjuj+cbe9Obr/yOk3R/eP/M5HovsuAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1ODEy0ZHH/jyvBHR/YHRfxTdP/1tL0b3L7hvQnR/4QfHR/evGnpndH/fGZdG988d+fno/v77Tojuv3vyGdH9KVP3R/d/PPHg6P7kM0+K7k87/63R/UfWfjy67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN3vvK9dEHzl2xNbr/9G2nRPdvOPyQ6P6YkU9E9/desyC6/63xN0b3d39wOLr/B5/+dXT/+BHnRvdPnv1ydP/uo0ZF9xeMvSO6v+iuh6L7K0/7y+j+nNe/E913AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQZ+Onxt9IETPjUjun/I4tui+3NHHB/dn3n+UdH9i1+7Nbq/8t8Piu7v/O306P7cWx6J7l+78oHo/gdeHR/d//Dx10f333jopOj+7ufeGt1fvuC06P57H/pFdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGnjTVVOjD8w679bo/j1b9kT3H1tyRXT/1qlzo/uPTvu96P710/dG9xf/amZ0f8Zv5kf3jx57U3R/7VNHR/dXrD4qun/qiunR/e8+Mi+6f9jZ34zuP/w3G6P7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTA5/ZNjD7w028sie6/eNU90f29JxwR3V8x9Mvo/vp3bYnuX/PMUHR/zLhl0f0D/29ldP/vZq2O7h//33Oj+4cdfFx0//JX50f3F7xyV3T/nyc9E91//q+2RfddAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAqcFjf3R/9IFr14yN7q8bvjm6v+z33xPd3/+ur0T3n/uTK6P7y879cHT/zZ84I7p/5zEzo/tTb9ka3Z/4vlOj+5+/YE50f9cRU6P7T249Mro/4cLro/uP/yr797sAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg9f82xXRB459Ylt0/5Mb3hHdf+mbv43uvzq0M7r/8JT7o/sbdo6O7r93xuHR/aVzX4vu/+K+h6P7r1wwPbo/OGJ3dP+62cPR/Xk7n4nu3/6OKdH932wbFd13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQY3D78efeDZy26P7k/78ezo/uon3xfdP+YfPxvd33zgOdH92X+4KLp/xPtvjO7/cudwdH/VpKHo/uZ3To3uL1z+T9H9Xafuju5vuTL7/138vydH93+y6qnovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1sPDQvdEH1my6OLr/rf1PR/f/+Oubo/uTzrknuv+xT14d3T9x/VPR/aMvuiu6/8Sdx0X3/+eHN0b3L1o7J7p/6fDy6P5Hrxyb3V+e/X0buu0t0f0btq+M7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSA2f/7PnoA0vnvxTdX3LJe6L7X/vK96L7iy6/OLr/hf2jo/sj/3VWdP/MtWOj+8vXXx7d/+K3Z0b3d5w0Jrr/tnUfiO4fetmq6P6oPV+I7o97Ivt9rj9lU3TfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBqc/F8Tog+Mu3tEdP/CMTOj+8vecl10f8rY86L7g9PnR/dn3PtsdH/w/oHo/t0Hfi66P+Ws7Pez5+Z/ie6v/sxno/tHHTAmuj/tpnuj+/O/viO6v2f8pui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDUwbddB0QcO2XdndP/GHyyO7o+85T+j+xuOvjq6v+bXj0f391yyKro/6vnvR/df3H52dH/e3++K7j92/r3R/QtGfya6v27aluj+1I1nRPdnDT8a3f/+kp9H910AAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAECpgZO/90D0ga0HnBXd3/TcadH9ofuOiO4f9Nqp0f2df3FedP9L110R3X9m8cXR/Q/96aXR/WN2/kN0/0Mn3h3dP/TBg6P7hz07P7o/68E7ovtzLn93dP/0n82M7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSgy+/cWD0gY9MXhPdv/PCCdH9tQMPRPcP++7k6P7SHW9E97dMXhfd37dxQ3T/lFEvR/cv+sYl0f2Fh5wV3X/hB49H97/6oyez+584Nro/5ct3RPevHnlNdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACU+v8AAAD//6s9hsMUXFJqAAAAAElFTkSuQmCC',
        'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANHklEQVR4nOzXjdfXdX3HcS69NsOLrrlj5g14Jip0mpe3826bdqMcnYWrcEeiG801ialbk6ENynTpPKHR2jliat7Mm2qYlocCOlRz3SAiRkioAeLA2pyDkQgDDybur3ids3Nej8cf8Ppwvj/ged6DBz9x4KikH45fFt3/ycSZ0f13HrYwur9r1sbo/omvPx/df2zvFdH9I4/4XHR/3a2PRPc/dObs6P53PrY0ur9xxbbo/ge/9s3o/g++sTq6v+Fzt0b3fz10anR/n+g6AP9vCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgPffPDK6AM3XDUc3V/7d1Oj+yPL3xnd/9k5C6L7B1yW/f5Dt+2I7v/3Rbuj+9O2zY3u73nfIdH9T+wzK7p/3bKro/ujNxwZ3b/7hd9E92etmRzdH/P8/Oi+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXw5oM+Hn3gnkXzovvTh98W3X/qTf8e3f/Mqiui+9NOuyW6/8SU86L73z3sZ9H9efuNj+4PPzsuun/qknuj+3ccOBLdX7/44ej+X7wyJrr/+rdnRvcPW/o30X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQauD20e+PPrBwz+nR/Zv+bWt0f966tdH9+yedH92/edOl0f0jz8j+vhOH50b3T14zO7q/+V3Z/TkDp0X3t1y3f3R/2usPRfd/9A8XRfc/vWRSdP9fT8r+/+ACACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDezz459HH3hu9GnR/UM+f3l0/4rx2T//79w6N7p/5o3nRvdX7Z0R3f/Mndnvc8HGD0T3H39H9vvff+0Po/sXvPmN6P7SjwxF98++76Lo/qYLdkX3J476ZHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo48qQ/iz6wzyuPRPdPv3ZCdH9gyrjo/vfWXxLdf/upD0X3r56+Prq/5KqLovsjX3pPdP+8i98b3d+8+0+j+7+49ubo/qHztkX31/70lOj+hrP/N7o/ZVH276cLAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNfDVlz4RfWDH+edG90e2jET3Zz3znej++z/1RHR/+fzs7zvu94ej+2+56vro/sPTj4juf+wPfxrdn/2hd0T3P7J9YnR/zf5zovv3nn1AdP+EcSdH97dv3BnddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGjhr+l+gDVxw7M7o/4dzbo/un7Xgyun/eHx8f3R+zeE10/3t3TYruP7pzTHR/aMbk6P7A8W+L7n/0jEXR/TE7boju3/vhZdH9BQu/Ft2ffNbs6P7gbx0T3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBhb8/bToA09OmBrdv3nFH0T3F8x5V3T/uPkro/tf2XpLdP/oO9dH9z87YU10/6jL94vuD/342ej+p/eORPe/dMuL0f1jF22O7n959fLo/kvjH4ruHzRufnTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBpc+Sc3RR+YfOZJ0f3Td18V3X/fzLOi+ysWvxLdv2bGlOj+3Blfie4PP7g6un/HjS9H90+4bWZ0f93V10T3R71pKDr//T1HR/f3Gzs2un//pB9F9/d9dEt03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQanDT9V9EHln9rfXR/+inbovvz11wa3f+P/zwlun/thR+M7q94ZGF0/5QDh6L79z09O7r/zIzJ0f0NL30xur9qfPbf14X/fFl0f93I7uj+ibeuiO5PPXh1dN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGrz0yp9HH3j5xb+M7v/tnAui+7sOHRfd333xC9H9i2edGN1ftfb70f1XD78nur/py/Oi+2PvvTy6P/Dgguj+tDuOie7v3bo7un/37WOj+yvf/l/R/elfOCS67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNHr79W9EH3v3Ye6L7vzf66Oj+cxfOiu7PenpqdP/jr/4iuv+D3ZdF9//qgZHo/qsHvDW6f/zjq6P7b1l+V3T/mu2HRvf/+us7ovuX3HVwdP/xkx+I7k+88ZrovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1MPrrT0cf+PAvD4/uH/Pcn0f37zvutuj+8YfeGN3/1cN7o/uPffK16P4jT50T3T//d5+J7n/7U89G9xd+flx0f92ZV2b3b/hGdP+w746N7i+65OLo/vxle6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTgyl/PjD7wTy+8HN1/7Sdzo/v7nnF9dP+jt30xun/p5Hui+0eNOii6/4+n3xndf/7J30T3t/zRzdH9+6dui+5PfHFxdP+m+2ZE9//nuH2j+zuHr4vuH7tkfXTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBr85Rtbow889dnh6P6UhZdH99/71ROi+1OvPyu6f+7V0flRvz2U/f5f+MAR0f0Jr10X3b977qLo/kPvfmt0f+nAnOj+A4/uje7vv2lzdH/nrnOi+9OOnh/ddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKX+LwAA//8ys4D/YLND5wAAAABJRU5ErkJggg==',
      ];
      let random_img = base64_images[(Math.floor(Math.random() * base64_images.length))];
      return "data:image/png;base64," + random_img;
    }
  }
};
</script>

<template>
  <div class="text-h5 q-pa-md">Εικόνες Web-Crawled ανά κλάση</div>

  <div class="row">
    <div class="col-6">
      <div class="q-pa-md q-gutter-sm">
        <q-banner rounded class="bg-blue-grey-2">
          <!--          In this service select a tag and receive images from the A.I. Model-->
          Σε αυτό το service επιλέξτε μια κατηγορία για να λάβετε εικόνες της ίδιας κατηγορίας
        </q-banner>
      </div>
    </div>
  </div>

  <div class="q-pa-md q-gutter-sm">
    <q-input v-model="image_count" label="Insert the number of images to return" style="max-width: 300px" />
    <p>Choose tag</p>
    <div class="q-pa-md q-gutter-md">
      <q-btn rounded v-for="(tag, index) in image_tags" v-bind:key="index" color="blue-grey-2" text-color="black"
        v-on:click="getSelectedTag(index)" class="cursor-pointer q-hoverable">{{ tag }}</q-btn>
    </div>
  </div>

  <div class="q-pa-md row items-start q-gutter-md">
    <template v-if="image_list">
      <div v-for="(image, index) in image_list" v-bind:key="index">
        <q-card class="my-card">
          <!--          <img src="https://random.imagecdn.app/500/150">-->
          <img 
            style="min-width: 500px;"
            :src=image.img_src 
          />

          <!-- <q-card-section>
            <div class="text-h6">{{ image.name }}</div>
            <div class="text-subtitle2">{{ image.brand }}</div>
          </q-card-section> -->

          <!-- <q-card-section class="q-pt-md justify-center row"> -->
            <div class="justify-center row q-pt-sm q-pb-sm">
              <!-- <q-btn disable flat size="md">{{ image_tag }}</q-btn> -->
               <div class="text-weight-bold" style="font-size: large">
                {{ image_tag }}
               </div>
            </div>
          <!-- </q-card-section> -->

        </q-card>
      </div>
    </template>
    <!--    <p v-else>No data received</p>-->
    <!-- <q-banner v-else dense rounded inline-actions class="text-white bg-red">
      No Tag selected
    </q-banner> -->
  </div>

</template>

<style scoped>
.my-card {
  width: 100%;
  max-width: 500px;
}
</style>
